name = "findartpro-add-lead-email"
main = "src/index.js"
compatibility_date = "2023-08-24"
usage_model = "bundled"
env = { }
kv_namespaces = [
  { binding = "fa_lead_emails", id = "9f7baab7d08c46a1a6f11b9a8e10598b" }
]

[triggers]
crons = [ ]
